name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.10
      - run: poetry install
      - run: poetry run flake8
      - run: poetry run mypy **/*.py
      - run: poetry run pytest --cov=coinbase_feed
      - uses: codecov/codecov-action@v2
